batchSize: 16
best_epoch: 0
best_thresh: 0.0
best_thresh_2fpr: 0.0
best_thresh_2tpr: 0.0
cvphase: 0
floss_alpha: 0.9
floss_gamma: 2.4
frametype: adjacent
lr: 0.001
model_dir: mobilenet_thyroid_weighted_focal_extralinear_adj_trainonly
modeltype: mobilenet
n_epochs_stop: 5
num_classes: 2
num_epochs: 100
phase: train
probFunc: Softmax
trainval: false
weightdecay: false
weightdecval: 0.003
weighted_sampler: true
