batchSize: 1
best_epoch: 99
best_thresh: 0.0
best_thresh_2fpr: 0.0
best_thresh_2tpr: 0.0
cvphase: 0
features2d: false
features3mm: false
featurestestfile: /will/update/automatically.csv
featurestrainfile: /will/update/automatically.csv
featurestrainvalfile: /will/update/automatically.csv
featuresvalfile: /will/update/automatically.csv
floss_alpha: 0.9
floss_gamma: 2.4
frametype: adjacent
lr: 0.001
modeltype: transformer
n_epochs_stop: 5
num_classes: 2
num_epochs: 100
numpatstest: 0
numpatstrain: 0
numpatsval: 0
phase: train
pos_encoding: false
probFunc: Softmax
trainval: true
vertconcat: false
weightdecay: false
weightdecval: 0.003
weighted_sampler: true
